services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/transfers_db?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: transfers_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Expose DB port for local debugging if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d transfers_db"]
      interval: 10s
      timeout: 15s
      retries: 5

volumes:
  postgres_data:
